### ISSUE TITLE
Client Id

### ISSUE THREAD

**Issue by superlevure** [dedoussis/icloud-hide-my-email-browser-extension#18]
Hi!

Your extension is using the [following](https://github.com/dedoussis/icloud-hide-my-email-browser-extension/blob/main/src/iCloudClient.ts#L136) Client Id to connect to Icloud: `d39ba9916b7251055b22c7f910e2ea796ee65e98b2ddecea8f5dde8d9d1a815d`

Is that ID tied to a personal account ?

**Comment by dedoussis** [comment]
Hey @superlevure!

This ID is **not** tied to a personal account nor a device. It is an OAuth2 public client ID that Apple has assigned to their own https://icloud.com/ web app.

These headers are used upon the iCloud authentication flow. Apple's authentication server keeps track of a set of registered client IDs (along with their redirect URIs) that are allowed to perform authentication.

Hence, this Client ID is tied to a client rather than a user. I assume that some other client ID is used when an iOS process attempts to authenticate against iCloud.

**Comment by dedoussis** [comment]
It should be possible to fetch this ID programmatically rather than hardcoding it into the source. This will prevent the extension from breaking in the infrequent scenario of Apple rotating the registered client ID of https://icloud.com

**Comment by superlevure** [comment]
Thanks for the explanation! I've looked at network exchanges when login to https://icloud.com and indeed that token is used by Apple. 

Thank you for the very useful extension
