### ISSUE TITLE
2FA Wonkiness w/ Firefox

### ISSUE THREAD

**Issue by JoeCotellese** [dedoussis/icloud-hide-my-email-browser-extension#20]
Hi, I'm trying to use the extension in Firefox. My Apple account has 2FA enabled.

When I enter my email / password and get the 2FA prompt the extension login window goes away. When I click again, I get an empty login window rather than a prompt to enter 2FA.

**Comment by dedoussis** [comment]
Hi @JoeCotellese! Thanks a lot for flagging this issue. I have managed to replicate it on my setup.

### Temporary work-around

<img width="415" alt="image" src="https://user-images.githubusercontent.com/24495755/213863459-b6e156d6-da77-415e-840c-562f141213df.png">

After entering the email and password, hit the "Enter" key of your keyboard rather than clicking on the "Sign In" button. This should keep the extension pop-up open, letting it to transition to the next page which is the 2FA code authentication:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/24495755/213863706-1498a63e-67f3-4811-89e0-c33ff4118404.png">

It is important that you do not navigate away from the pop-up before it has transitioned to the 2FA page.

### Why this happens?

1. The extension is implemented as a state machine where each state represents a different page of the extension. The initial state is the sign-in page.
1. When submitting the sing-in form, the extension makes a sign-in request to the iCloud servers and waits for a response. The extension is designed to transition to the next state (2FA code authentication page) only upon the reception of a successful sign-in response from iCloud.
1. The iCloud backend pushes a 2FA notification to each of your authenticated devices.
1. The notification arrives at your device. A new MacOS dialog pops up which causes Firefox to close the extension pop-up before the extension receives the successfull sign-in response from iCloud.
2. The extension has not transitioned to the next state, even though the sing-in was successful. The extension is gong to render the initial sign-in state once the user re-opens the pop-up.

Essentially, this is a race condition between the 2FA notification arriving at the device and the extension receiving the successful sign-in response.

This behaviour does not happen on Chrome. There are very few cases where Chrome will close the extension pop-up without the user taking any action (such as a click outside the pop-up, or hitting the "Esc" key).

@JoeCotellese Let me know if the work-around works for you for the time being. I will be looking into putting a proper fix together.

**Comment by dedoussis** [comment]
Similar issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1378527

**Comment by JoeCotellese** [comment]
It took a few tries but that did the trick. Thanks!

**Comment by mounta11n** [comment]
i had the same issue, but your temp workaround solved it perfetcly! thanks a lot

**Comment by rafacampoamor** [comment]
Tried several times but couldn't get it to work (though it worked on Edge). Isn't it possible to open the log in dialog in a new popup window?

**Comment by dedoussis** [comment]
Hi @rafacampoamor! Yes, it is possible to open the pop-up as a normal tab:
1. Open the pop-up and right-click on its background
2. Select "View Page Source". This will open a new tab with a URL that would look something like this: `view-source:moz-extension://e39b22ff-52d1-4346-bd41-5b4fc89bf114/popup.html`.
3. Remove the `view-source:` prefix and you have a URL pointing to the pop-up: `moz-extension://e39b22ff-52d1-4346-bd41-5b4fc89bf114/popup.html`.
4. Enter the URL and the pop-up interface would be opened as a regular web-page.

Note that pop-up URLs are unique per installation. Copy-pasting the above URL of mine won't work. You need to retrieve the URL of your own installation of the extension.

**Comment by dedoussis** [comment]
FYI, I've started working on a proper fix to this issue a few weeks ago but never got around to shipping it. I hope I will get some time by the end of the month to wrap this up.

**Comment by rafacampoamor** [comment]
@dedoussis It worked! Thank you so much for the workaround!

**Comment by Futos** [comment]
> Hi @JoeCotellese! Thanks for taking the time to flag this issue. I have managed to replicate it on my setup.
> ### Temporary work-around
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/24495755/213863459-b6e156d6-da77-415e-840c-562f141213df.png">
> 
> After entering the email and password, hit the "Enter" key of your keyboard rather than clicking on the "Sign In" button. This should keep the extension pop-up open, letting it to transition to the next page which is the 2FA code authentication:
> 
> <img alt="image" width="412" src="https://user-images.githubusercontent.com/24495755/213863706-1498a63e-67f3-4811-89e0-c33ff4118404.png">
> 
> It is important that you do not navigate away from the pop-up before it has transitioned to the 2FA page.
> ### Why this happens?
> 
>     1. The extension is implemented as a state machine where each state represents a different page of the extension. The initial state is the sign-in page.
> 
>     2. When submitting the sing-in form, the extension makes a sign-in request to the iCloud servers and waits for a response. The extension is designed to transition to the next state (2FA code authentication page) only upon the reception of a successful sign-in response from iCloud.
> 
>     3. The iCloud backend pushes a 2FA notification to each of your authenticated devices.
> 
>     4. The notification arrives at your device. A new MacOS dialog pops up which causes Firefox to close the extension pop-up before the extension receives the successfull sign-in response from iCloud.
> 
>     5. The extension has not transitioned to the next state, even though the sing-in was successful. The extension is going to render the initial sign-in state once the user re-opens the pop-up.
> 
> 
> Essentially, this is a race condition between the 2FA notification arriving at the device and the extension receiving the successful sign-in response.
> 
> This behaviour does not happen on Chrome. There are very few cases where Chrome will close the extension pop-up without the user taking any action (such as a click outside the pop-up, or hitting the "Esc" key).
> 
> @JoeCotellese Let me know if the above work-around works for you for the time being. I will be looking into putting a proper fix together.

This Workaround is not working for me on Mac OS Firefox 110. If I use enter instead of clicking the button it still closes my popup

**Comment by dedoussis** [comment]
> Hi @rafacampoamor! Yes, it is possible to open the pop-up as a normal tab:
> 
> 1. Open the pop-up and right-click on its background
> 2. Select "View Page Source". This will open a new tab to a URL of the following format: `view-source:moz-extension://e39b22ff-52d1-4346-bd41-5b4fc89bf114/popup.html`.
> 3. Remove the `view-source:` prefix and you have the URL of the pop-up: `moz-extension://e39b22ff-52d1-4346-bd41-5b4fc89bf114/popup.html`.
> 4. Open a new tab, enter that URL and the pop-up interface would be rendered as a regular web page.
> 
> Note that pop-up URLs are unique per installation. Entering the above URL of mine won't work. You need to retrieve the URL of your own installation of the extension.

@Futos you could try using the above workaround ☝️
