### ISSUE TITLE
[Feature request] Thunderbird extension

### ISSUE THREAD

**Issue by FxRe** [dedoussis/icloud-hide-my-email-browser-extension#64]
First of all, thank you for this extremely useful extension, Dimitrios! It's working really well and I use it a lot.

I admit that I have no clue how similar Firefox and Thunderbird extensions are, but I hope they're somewhat related and my request wouldn't mean a completely new integration from scratch.

It would be fantastic, if it was possible to create new email addresses from within Thunderbird. Basically copying the functionality of Apple's own Mail app on macOS and iOS, where you can opt to generate a new address when selecting the "send from" email account.

Is this something you could imagine implementing in the future?

**Comment by teeberg** [comment]
@FxRe That may seem useful at first, but what exactly would that do? I imagine you would like to create addresses and send emails from those, but that's practically impossible to do.

Hide My Email is mostly meant to help in *receiving* emails and not sending them. Until somebody messages you on a hidden email, you can't really know what the apple-encoded email looks like that you would need to send an email to any given recipient.

That's actually bit me a few times where companies have asked me to send an email to some email address that they couldn't send me an email from, to make sure it's my email address. I couldn't comply since there was no way for me to know to which encoded email address to send it to.

**Comment by FxRe** [comment]
Thanks for your reply @teeberg 

I _think_, I understand what you mean. The current Hide My Email extension simply creates a new alias and when an email is sent to the address with that new alias it's being forwarded to the main iCloud email address.
However, sending an email would require additional information like the apple-encoded email address and possibly more, which we don't have, and probably can't easily be reverse engineered, if possible at all.

My idea was really just to replicate exactly whatever Apple is doing with its own Mail app when you send an email and select "hide my address". That would especially be useful on Linux and Windows, where Apple Mail isn't available.

**Comment by teeberg** [comment]
Ooh yeah I have used that feature in Apple's Mail app as well. That would be super-neat if that would work in Thunderbird. I don't know if that mechanism has been fully published, though. Could require some reverse engineering...
