### ISSUE TITLE
DOM shouldn't be changed by the extension

### ISSUE THREAD

**Issue by dylankenneally** [dedoussis/icloud-hide-my-email-browser-extension#9]
## Issue
When I click on an email field, the extension injects items into the DOM & thus fiddles with a site's rendered output. Whilst the injected items are helpful & form a big part of the extension's functionality, it's inappropriate for the DOM to be updated by the extension in this way, as it can lead to odd effects happening for the site being visited & shouldn't happen.

Furthermore, it presumes that users will want a new hidden email address for each email field, but this is not the case.

## Steps to replicate
1. Installed & enabled the extension
1. Visit any site/page with an email form field, e.g. https://github.com/settings/emails, and note the rendered output:
    - <img width="860" alt="Add email address" src="https://user-images.githubusercontent.com/12589363/202978474-7b7903e2-dcb5-49c4-8d29-ef4fdf2d97f0.png">
1. Click the email field and note the rendered output
    - <img width="860" alt="Add email address" src="https://user-images.githubusercontent.com/12589363/202978600-8b95b428-3572-46f8-b2df-f0b7fefe2f49.png">

## Expected/desired outcome
- Add the access point for the functionality to the context menu for the email field instead
- <img width="372" alt="image" src="https://user-images.githubusercontent.com/12589363/202979480-e4863180-3e27-420c-8198-8acb3545fffa.png">

## Platform details
Hardware: MacBook Pro (Retina, 15-inch, Mid 2015)
OS: macOS Monterey, v12.6
Browser: Google Chrome, Version 107.0.5304.110 (Official Build) (x86_64)
Extension: iCloud Hide My Email, v1.0.0

## Side notes
- Thank you for the extension, it's very helpful
- If you agree with the issue & expected outcome, I'd be happy to take the issue on myself.

**Comment by dedoussis** [comment]
Hey @dylankenneally ! Thank you for this feedback and for taking the time to put such a detailed issue together.

I agree with your take. At the moment the extension modifies the DOM in a pretty aggressive manner. 

Originally I took the inspiration for this functionality from the [1Password extension](https://chrome.google.com/webstore/detail/1password-%E2%80%93-password-mana/aeblfdkhhhdcdjpifhhbdiojplfjncoa). 1Password also modifies the DOM, but in a much more discrete way. 1Password injects an iframe as the last child of the body element and the iframe loads a static file that is baked into the extension. Unfortunately I was lacking the time to implement such a sophisticated DOM modification, leading to the current suboptimal result.

I do think that your context menu idea is excellent and I would love to see it introduced in this extension. However, rather than sunsetting the current DOM mutating functionality I would rather keep both and let the user pick their favourite (or both) through the Options page of the extension.

Feel free to take this yourself. Send any questions you may have my way (I'll try to be more swift with my responses).

**Comment by dylankenneally** [comment]
Letting users pick which UI scheme they want sounds like a good way to go. It's probably a good idea to leave the existing UI as as the default choice too -  otherwise existing users that get auto-updated in Chrome could be left scratching their heads. 

I'm happy to take this on, I'll send a PR over when it's ready.

**Comment by he3als** [comment]
Any updates on this? No rush, just curious

**Comment by dylankenneally** [comment]
I've had zero time to look at it @he3als - it's on my list, but that list isn't getting any shorter. 

If someone else wants to take it on, that's cool, as I can't say when this will make it to the top of my todo list.

**Comment by dedoussis** [comment]
Started working on this: https://github.com/dedoussis/icloud-hide-my-email-browser-extension/pull/32

Will finish at some point next week.

**Comment by dedoussis** [comment]
This change ended up being more complex than what I was expecting. Have merged the PR.

I won't publish it to the web store right away though. I want to spend a few days using the new version on my machine to make sure that I haven't introduced any regression. You can get a sneak preview of the new functionality from the screenshots in the updated README (main branch).

Will close this as soon as I publish the new version to the chrome and firefox webstores.

**Comment by dedoussis** [comment]
Have submitted the new version to both of the Chrome and Firefox stores. The Firefox one has already been accepted. Might take a few days to be accepted in Chrome. Thanks everyone for your feedback on this one; closing.

**Comment by dedoussis-stripe** [comment]
Has also been published in the chrome web store. Let me know if you spot any issues.

**Comment by dylankenneally** [comment]
@dedoussis - got the latest update, it works a treat

Really appreciate the work you've put in to this, next time I'm in London (my old home town), I'll have to buy you a beer to say thank you
